### ISSUE TITLE
What about optional params in the endpoint?

### ISSUE THREAD

**Issue by tutyamxx** [calvintwr/express-routemagic#10]
What if we have something like `v1/getstuff/:id?` as parameter ?

**Comment by calvintwr** [comment]
@tutyamxx it will be “routes/v1/getstuff.js”. And inside “getstuff.js”, you will write:

```
router.get('/:id', (req, res, next) => {
    // do something with req.params.id
})
```

**Comment by tutyamxx** [comment]
Thanks for answering, however I think I'm either stupid or I can't seem to find a way to run it properly. If you clone and run the example code you provided, try accessing `foo.js`. It says can't GET foo

**Comment by calvintwr** [comment]
Can you share your repo with me? @calvintwr

**Comment by tutyamxx** [comment]
It's your repo @calvintwr https://github.com/calvintwr/express-routemagic-eg


ain't working properly on windows though as i mentioned above

**Comment by calvintwr** [comment]
hi @tutyamxx indeed i found out that there are compatibility issues with windows. I fixed it with https://github.com/calvintwr/express-routemagic/commit/80347f51506d89d618bceee89ea9d8c34312534f

Can you delete the clone and install a fresh one so that it pulls the latest version (2.0.6) that has this fix. And let me know if it works?

**Comment by tutyamxx** [comment]
sure, will do tonight and let you know :)

**Comment by calvintwr** [comment]
@tutyamxx thanks for opening the issue!
